### ISSUE TITLE
QueryHost doesn't support fields=availableMemoryCapacity,availableCpuCapacity

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#180]
>>>QueryHost  fields=availableMemoryCapacity
API call[org.zstack.header.message.APIReply] failed because [code: SYS.1000, description: An internal error happened in system, details: org.hibernate.QueryException: could not resolve property: availableMemoryCapacity of: org.zstack.header.host.HostVO [select hostinventory.availableMemoryCapacity from org.zstack.header.host.HostVO hostinventory]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: availableMemoryCapacity of: org.zstack.header.host.HostVO [select hostinventory.availableMemoryCapacity from org.zstack.header.host.HostVO hostinventory]]
API call[org.zstack.header.message.APIReply] failed because [code: SYS.1000, description: An internal error happened in system, details: org.hibernate.QueryException: could not resolve property: availableMemoryCapacity of: org.zstack.header.host.HostVO [select hostinventory.availableMemoryCapacity from org.zstack.header.host.HostVO hostinventory]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: availableMemoryCapacity of: org.zstack.header.host.HostVO [select hostinventory.availableMemoryCapacity from org.zstack.header.host.HostVO hostinventory]]

**Comment by zxwing** [comment]
This is not a bug. it's by design. 
availableMemoryCapacity, totalMemoryCapacity, availableCpuCapacity, totalCpuCapacity are not the party of the host table; they are actually in HostCapacityVO table, though we use some trick to put them as the part of host inventory. The premitive fields of an inventory are documented in the user manual, for example, http://zstackdoc.readthedocs.org/en/latest/userManual/host.html#primitive-fields-of-query.

However, I put a fix in below commit so user will get a clear error message.
2d3611772eed74463f75d296e9645afa514c782e
