### ISSUE TITLE
VM console is not available

### ISSUE THREAD

**Issue by peter-wangxu** [zstackorg/zstack#211]
FAILURE
REQUEST

{
  "org.zstack.header.console.APIRequestConsoleAccessMsg": {
    "vmInstanceUuid": "93ace80c440147b693bc8137c02d3ea7",
    "session": {
      "uuid": "918e72fce64b4466b6743d9466825971"
    }
  }
}
RESPONSE

{
  "org.zstack.header.console.APIRequestConsoleAccessEvent": {
    "success": false,
    "apiId": "4f2690b3a2bd4036848d5b6aebec48b1",
    "headers": {
      "schema": {}
    },
    "error": {
      "code": "SYS.1006",
      "description": "An operation failed",
      "details": "the console agent is not connected; it's mostly like the management node just starts, please wait for the console agent connected."
    },
    "id": "d3833858682640ec947b2f7aa2211e7a",
    "creatingTime": 1456048291645
  }
}

**Comment by zxwing** [comment]
This is an expected behavior for current ZStack. Every time the management node boots, it takes some time to deploy the console proxy agent; during the period, you will get the error above when you try to connect to a console because the console proxy is not ready.

The console proxy is written in Python, which will compile every time during deployment. We will replace it with a golang version that will significantly the deploying process.

**Comment by zxwing** [comment]
Peter, our QQ group is 410185063 which has lots of users discussing issues there. If you speak Chinese, welcome to join !
