### ISSUE TITLE
zstack 只有 rabbitmq runtime failover，没有启动rabbitmq failover

### ISSUE THREAD

**Issue by syuanwei** [zstackorg/zstack#216]
当rabbitmq服务器有多台运行时（mq0,mq1,mq2）,CloudBus.serverIp.0指定的服务器突然故障,使用zstack-ctl start启动服务时，zs不会自动切换故障的服务器。

**Comment by youyk** [comment]
Thanks report this issue. We original assume user should fix broken rabbitmq-server,  when start zstack. Because this should be right time to resolve rabbitmq issue. If user don't resolve the rabbitmq ha issue, he should remove the config from zstack.properties. Otherwise user might be not able to find 1 rabbitmq-server is broken.
