### ISSUE TITLE
Wrong imagesize on webui

### ISSUE THREAD

**Issue by joubertredrat** [zstackorg/zstack#289]
Hi guys,

I'm downloading CentOS7 image, but on all times, is displayed wrong size, as below.

![zstack_image_all](https://cloud.githubusercontent.com/assets/1520407/16508577/b2095ff4-3f0a-11e6-8954-ce410938e235.jpg)

![zstack_image](https://cloud.githubusercontent.com/assets/1520407/16508583/b7ac506a-3f0a-11e6-9de0-463cb9514f23.jpg)

``` bash
[root@zstack 2b0b13e12af24f9f8e32dfd735ddac79]# pwd
/backupStorage/rootVolumeTemplates/acct-36c27e8ff05c4780bf6d2fa65700f22e/2b0b13e12af24f9f8e32dfd735ddac79
[root@zstack 2b0b13e12af24f9f8e32dfd735ddac79]# ls -lah
total 871M
drwxrwxrwx. 2 root root   50 Jun 28 22:50 .
drwxrwxrwx. 6 root root 4.0K Jun 28 22:50 ..
-rw-rw-rw-. 1 root root 871M Jun  7 19:04 CentOS-7-x86_64-GenericCloud.template
```

**Comment by joubertredrat** [comment]
Sorry guys, on version 1.3 display size and actualsize, then, isn't possible to add both columns on table?

**Comment by ghxandsky** [comment]
@joubertredrat With zstack-cli, command 【QueryImage】 get virtual size and【SyncImageSize】get actual size.

**Comment by youyk** [comment]
@joubertredrat yeah. The zstack-dashboard doesn't show the real size of image. We will try to expose more functions in UI in the future.

Since you are playing with ZStack deeply, I would recommend a better product which is built upon ZStack, which implement almost all UI features (including both real size and virtual size of Volume). 
It is mevoco. http://www.mevoco.com/en/ 

![image](https://cloud.githubusercontent.com/assets/2962014/16526508/2738ba20-3fe4-11e6-902e-391a487c3f63.png)

Currently the website is lacking of enough English introduction. But I think it will be easy for you to install and play, since is similar with ZStack.

**Comment by joubertredrat** [comment]
Hi guys,

@youyk Mevoco is open source too?

**Comment by youyk** [comment]
@joubertredrat Mevoco is based on ZStack, but it is not open source. Mevoco UI is a better example to show ZStack API capabilities.
