### ISSUE TITLE
Create Data Volume From Volume Snapshot failed when origianl voluem is deleted in Local Primary Storage

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#64]
The error log is like:

ApiError: API call[org.zstack.header.volume.APICreateDataVolumeFromVolumeSnapshotEvent] failed because [code: SYS.1006, description: An operation failed, details: all candidate primary storage can not handle hypervisor volume snapshot[hypervisorType:KVM, uuid:2d17ae96f3cd4e53a62145719f00490e]]

The reproduced step:

1. Create VM
2. Create Volume and attach to VM
3. Create Volume snapshot
4. backup volume snapshot
5. Delete Volume
6. Try to create new Volume from previous volume snapshot.

**Comment by zxwing** [comment]
creating template from backup volume snapshot is considered to remove since local storage. This scenario is too complex to support if the backup storage and primary storage are separate storage system, because the primary storage needs a 'jumping storage' to download snapshots and do the merge operation, which are complicated and even impossible for some sotrage systems(e.g. commercial block-based iscsi storage, distributed storage system). We will dump this scenario.
