### ISSUE TITLE
The PS capacity is not reduced correctly, when attach Data Volume to NFS Primary Storage. 

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#67]
1. Create 1 VM
2. Create a Volume
3. Attach the Volume to VM. The volume size is 10485760. But in PS capacity, the capacity is only reduced 10475200. And check the file in system, it's real size is 10813440. 

[root@centos61 Packages]# ls -l /opt/zstack/nfsprimarystorage/prim-917c95b2e39943d0b7d31469bc23db05/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-1a080f619eed42b083a92bbc44d884e9/1a080f619eed42b083a92bbc44d884e9.qcow2
-rw-rw-rw-. 1 root qemu 10813440 Jul 10 13:10 /opt/zstack/nfsprimarystorage/prim-917c95b2e39943d0b7d31469bc23db05/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-1a080f619eed42b083a92bbc44d884e9/1a080f619eed42b083a92bbc44d884e9.qcow2

    "inventory": {
        "createDate": "Jul 10, 2015 1:05:15 PM",
        "deviceId": 1,
        "diskOfferingUuid": "c83c641770c44af386dcf7ce93e15e7c",
        "format": "raw",
        "installPath": "/opt/zstack/nfsprimarystorage/prim-917c95b2e39943d0b7d31469bc23db05/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-1a080f619eed42b083a92bbc44d884e9/1a080f619eed42b083a92bbc44d884e9.qcow2",
        "lastOpDate": "Jul 10, 2015 1:05:15 PM",
        "name": "test",
        "primaryStorageUuid": "917c95b2e39943d0b7d31469bc23db05",
        "size": 10485760,
        "state": "Enabled",
        "status": "Ready",
        "type": "Data",
        "uuid": "1a080f619eed42b083a92bbc44d884e9",
        "vmInstanceUuid": "ab73cae16c9642d29e05a0673fc99bca"
    },

        {
            "attachedClusterUuids": [
                "3d7d0c992e0b4d638d3b5b9977dcc76b"
            ],
            "availableCapacity": 50959220735,
            "availablePhysicalCapacity": 50969695935,
            "createDate": "Jul 10, 2015 12:53:27 PM",
            "description": "Test",
            "lastOpDate": "Jul 10, 2015 12:53:27 PM",
            "mountPath": "/opt/zstack/nfsprimarystorage/prim-917c95b2e39943d0b7d31469bc23db05",
            "name": "nfs",
            "state": "Enabled",
            "status": "Connected",
            "totalCapacity": 50969706496,
            "totalPhysicalCapacity": 50969706496,
            "type": "NFS",
            "url": "zstack:/home/nfs",
            "uuid": "917c95b2e39943d0b7d31469bc23db05",
            "zoneUuid": "5336c32ab7a34fc2afe3c05766c8ac6f"
        }

The PS primary storage totalCapacity and

**Comment by zxwing** [comment]
you may do a wrong math. totalCapacity(50969706496) - availableCapacity(50959220735) = 10485761 which is 1 byte bigger than the volume size(10485760), not 10475200. The extra 1 byte is wried. I tried to repdouce but cannot. 

To check the volume size on disk, you should use qemu-img like:

qemu-img info /opt/zstack/nfsprimarystorage/prim-406dd2cde78a4ddfbc4b201a1fc70bc0/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-1a6fa3a5e70d412880fbbc1679fb8305/1a6fa3a5e70d412880fbbc1679fb8305.qcow2
image: /opt/zstack/nfsprimarystorage/prim-406dd2cde78a4ddfbc4b201a1fc70bc0/dataVolumes/acct-36c27e8ff05c4780bf6d2fa65700f22e/vol-1a6fa3a5e70d412880fbbc1679fb8305/1a6fa3a5e70d412880fbbc1679fb8305.qcow2
file format: qcow2
virtual size: 1.0G (1073741824 bytes)
disk size: 272K
cluster_size: 65536

Because of the thin-provisioning, the size checked by command 'll' is not different that the users asked
