### ISSUE TITLE
None existed NFS could be added in Primary Storage, if PS is not attached to any cluster

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#9]
Thanks for GranceXia  to report this issue. 

![image](https://cloud.githubusercontent.com/assets/2962014/7296671/3ee33110-e9f4-11e4-87ce-51ce44bab8d9.png)

The red box in above picture show 3 PS are connected successfully. But actually ps-thtz ps-ep5r do not exist. although the PS validation need a host to do, the PS status should not show ***connected***.

**Comment by zstackorg** [comment]
The status of NFS primary storage will always show connected. As a primary storage can be attached to multiple clusters, one cluster fails to attach (because of hosts fails to mount NFS) doesn't mean the primary storage cannot work for other clusters. Given this fact, we cannot put NFS primary storage into Disconnected. In future UI, we may hide status field for NFS primary storage.
